---
- hosts: all
  become: yes
  tasks:
    - name: Check that the the /usr/lib/jvm/java-8-openjdk-amd64 exists
      stat:
        path: /usr/lib/jvm/java-8-openjdk-amd64
      register: java_result

    - name: Update apt-cache
      apt: update_cache=yes
      when: java_result.stat.exists == False

    - name: Install packages needed for installing spring-petclinic
      apt: pkg={{ item }}
      with_items:
        - openjdk-8-jdk
      when: java_result.stat.exists == False

    - git:
        repo: 'https://github.com/spring-projects/spring-petclinic.git'
        dest: /tmp/git_repo/

    - name: Install spring-petclinic
      shell:
        cmd: ./tmp/git_repo/spring_petclinic/mvnw spring-boot:run
        #chdir: /tmp/git_repo/spring_petclinic/

    #- name: Remove tmp files used for spring-petclinic installation
    #  file: path={{ item }} state=absent
    #  sudo: yes
    #  with_items:
    #    - /tmp/spring-petclinic
