---
- hosts: all
  become: yes
  tasks:
    # Set passwordless sudo
    - lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - shell: /usr/bin/uptime
      register: result

    - debug:
        var: result
        verbosity: 2

    # Check is necessary since spring-petclinic need Java 1.8 to run
    - name: Check that the the /usr/lib/jvm/java-8-openjdk-amd64 exists
      stat:
        path: /usr/lib/jvm/java-8-openjdk-amd64
      register: java_result

    - name: Update apt-cache
      apt: update_cache=yes
      when: java_result.stat.exists == False

    # Not tested yet
    - name: Install packages needed for installing spring-petclinic
      apt: pkg={{ item }}
      with_items:
        - openjdk-8-jdk
      when: java_result.stat.exists == False

    - git:
        repo: 'https://github.com/spring-projects/spring-petclinic.git'
        dest: /tmp/spring_repo/

    # Add check if .jar already exists
    - name: Navigate to spring-petclinic folder and build
      command: chdir=/tmp/spring_repo ./mvnw package

    - name: Check that the /tmp/spring_repo/target/spring-petclinic-2.2.0.BUILD-SNAPSHOT.jar exists
      stat:
        path: /tmp/spring_repo/target/spring-petclinic-2.2.0.BUILD-SNAPSHOT.jar
      register: build_result

    #- debug:
    #    msg: Build successful. Running spring-petclinic application.
    #  when: build_result.stat.exists == True

    # Only run if executable is available
    - name: Run spring-petclinic application
      command: chdir=/tmp/spring_repo/target java -jar spring-petclinic-2.2.0.BUILD-SNAPSHOT.jar
      when: build_result.stat.exists == True
