---
- hosts: all
  become: yes
  #become_method: sudo
  #become_user: root
  #become_ask_pass: no
  tasks:
    - name: Install spring-petclinic
      #sudo: yes
      package:
        name: spring-petclinic

    - name: Start spring-petclinic
      #sudo: yes
      service:
        name: spring-petclinic
        enabled: yes
        state: started

    - name: Set attributes
      set_stats:
        data:
          site_config_dir: /etc/spring-petclinic/conf.d
